### ISSUE TITLE
Cannot edit User row

### ISSUE THREAD

**Issue by AmbroiseCollon** [ParsePlatform/parse-dashboard#119]
I have been trying parse dashboard open source. And old hosted dashboard too. I've set them up so that they both access the same app hosted on heroku +mongodb. They both works fine.

On my User class, I've added an `index` column of type `Number`. I tried to edit my User manually in the dashboard to give each one an incrementing index. I've done it several times on open source dashboard and when I refresh the page my modification was not saved. While on hosted, it worked as expected the first time. Why is that ?

**Comment by peterdotjs** [comment]
@AmbroiseCollon can you take a screenshot of the network/console when you try to update? It'll help determine if it's an issue with the server or the dashboard.

**Comment by AmbroiseCollon** [comment]
Here is the request that is shot : 

    {"index":2,"_method":"PUT","_ApplicationId":"blablaf","_ClientVersion":"js1.6.14","_MasterKey":blabla","_InstallationId":"blabla"}`

And the headers :
```
Referer	http://localhost:4040/apps/MyApp/browser/_User
Content-Type	text/plain
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_11_3) AppleWebKit/601.4.4 (KHTML, like Gecko) Version/9.0.3 Safari/601.4.4
Origin	http://localhost:4040
```
But it keeps trying but never get a response. Which is weird because it works as I said it works on old hosted dashboard and all similar requests works perfectly on new open source dashboard.

There is nothing in the console.

**Comment by peterdotjs** [comment]
What version of parse-server are you running? By no response are you saying the request is in `pending` state? There were some issues with `_User` in parse server 2.1.4 that were resolved in 2.1.5.

**Comment by AmbroiseCollon** [comment]
I have indeed an older version of Parse server. How is that linked to my issue though as it works on old dashboard ? Thanks !

**Comment by peterdotjs** [comment]
Updating may or may not solve the issue but it'll be easier for us to troubleshoot if we're on the same versions. For now until we release a specific version I would recommend using the master branch of the dashboard the latest release version of Parse Server. Once you've updated let me know if you're still getting the issue and we'll go from there.

**Comment by AmbroiseCollon** [comment]
I have updated to 2.1.5 and I still have the issue for all columns. Sorry that I wasn't on the last version.

**Comment by peterdotjs** [comment]
Could you provide a screen shot of the the browser debugger network tab? When you said the request was "pending" it sounds like an issue with parse-server but a screenshot would help confirm this.

This request payload you listed above is for adding a new column for user which was the exact issue that 2.1.4 was having. This makes me suspect that 2.1.5 might not be getting picked up.

**Comment by AmbroiseCollon** [comment]
Here you go. Just to be really clear, I'm not adding a column, I am just editing a value in an existing column.
<img width="1440" alt="capture d ecran 2016-03-14 a 17 46 31" src="https://cloud.githubusercontent.com/assets/2622390/13752034/2f5fbb7c-ea0d-11e5-8c3c-b6394c3688f6.png">

**Comment by peterdotjs** [comment]
What is the response when you run the same curl command through a terminal?

It seems like your parse-server is unreachable which is odd since you've already gotten as far as this.

**Comment by AmbroiseCollon** [comment]
Sorry I don't use curl. Need help on that :)

**Comment by AmbroiseCollon** [comment]
Btw, I've just updated to Parse Server 2.1.6 and it does not work either. But everything else still works fine (class creation, updates and addition in other class etc.).

**Comment by peterdotjs** [comment]
In the curl command can you replace `api.parse.com` with that of your own parse server? This was fixed in #145

**Comment by AmbroiseCollon** [comment]
Maybe unrelated but I've updated my parse dashboard to include latest fixes and the run fails : 
`
[npm-debug.txt](https://github.com/ParsePlatform/parse-dashboard/files/174549/npm-debug.txt)

`

**Comment by AmbroiseCollon** [comment]
Still if run the curl command with my server instead of `api.parse.com`, I get : 
```
curl: (60) SSL certificate problem: Invalid certificate chain
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle"
 of Certificate Authority (CA) public keys (CA certs). If the default
 bundle file isn't adequate, you can specify an alternate file
 using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in
 the bundle, the certificate verification probably failed due to a
 problem with the certificate (it might be expired, or the name might
 not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use
 the -k (or --insecure) option.
```
And if i had the `-k`option, I get nothing.

**Comment by peterdotjs** [comment]
I think there is something wrong with the query. Could you paste your query? As well as the type of value you are trying to add?

**Comment by AmbroiseCollon** [comment]
<img width="728" alt="capture d ecran 2016-03-16 a 10 51 02" src="https://cloud.githubusercontent.com/assets/2622390/13808237/797fa588-eb65-11e5-8b9c-a4754b7b5466.png">

When I use master key, I get the same result (nothing).

**Comment by peterdotjs** [comment]
Unfortunately I'm unable to repro. Assuming you have an `index` field that is of `number` type - it works for me locally. As the curl command itself is failing it's an issue with parse-server and you should try posting an issue there. Seems specific to your data.

**Comment by AmbroiseCollon** [comment]
Ok I'll do so. Thanks for having a look !

**Comment by grantespo** [comment]
Same Problem.
